Major db-erase changes
* uses filter-tables
* is now more verbose when nothing to do
* accepts -f option, to force removals
* Xorg log conventions, such as EE, WW, II, ...
* patch tables are truncated rather than removed
* tmp files contain $db

diff --git a/db-erase b/db-erase
--- a/db-erase
+++ b/db-erase
@@ -1,78 +1,85 @@
 #!/bin/sh
-# Deletes all tables from the specified database.
+# Deletes all installed tables from the specified database.
 PATH=/bin:/usr/bin:$HOME/bin:${0%/*}
 
 . db-load-settings.sh
-. db-get-password.sh
-if [ "$?" != 0 ]; then
-    exit "$?"
-fi
+. db-get-password.sh;
 
-existing_tables=`mysql $db -p"$PASSWORD" -e"show tables"`
-if [ ! "$?" = 0 ]; then
-    exit 2
-fi;
-if ! echo $existing_tables | egrep 'patch_history' >/dev/null; then
+function get_tables {
+    if ! mysql $db -p"$PASSWORD" -e"show tables" -N; then
+        exit 2
+    fi
+}
+
+if ! get_tables | egrep -x 'patches' >/dev/null; then
+    echo "db: nothing to erase in $db" 1>&2
     exit 0;
 fi
 
-history=/tmp/wipe-history.$$
-staged=/tmp/wipe-staged.$$
-last_error=/tmp/wipe-last-error.$$
-log=./db-$db.log
+history=/tmp/db-erase-$db-history.$$
+staged=/tmp/db-erase-$db-staged.$$
+last_error=/tmp/db-erase-$db-error.$$
+log=$CONFIG_ROOT/$db.log
+
 function cleanup {
     rm -f $staged $tables $last_error $history
 }
 trap cleanup EXIT
 trap 'echo; cleanup; exit 1' INT TERM
 
-if ! mysql $db -p"$PASSWORD" -e"select table_name,type,order_applied from patch_history" -N | egrep -v "Tables_in_$db" >$history; then
-    exit 2
-fi;
-cat $history | db-get-installed-tables.awk >$staged
+function get_history {
+    if ! mysql $db -p"$PASSWORD" -e"select table_name,type,order_applied from patch_history" -N; then
+        exit 2
+    fi;
+}
+
+get_history | db-get-installed-tables.awk | . db-filter-tables.sh >$staged
 if [ ! -s $staged ]; then
+    echo "db: nothing to erase in $db" 1>&2
     exit 0;
 fi;
 
-echo "Installed tables in $db:"
-cat $staged
-read -p"Destroy listed tables in $db? (y/n): " r
-case $r in
-    y*) ;;
-    *) exit 1
-esac
+if [ ! $FORCE ]; then
+    echo "Installed tables in $db:"
+    cat $staged
+    read -p"Destroy listed tables in $db? (y/n): " r
+    case $r in
+        y*) ;;
+        *) exit 1
+    esac
+fi
 
 tries=0
 errors=0
 while [ $tries -lt 20 ]; do
+    echo "[II] Starting erase, attempt $tries" >>$log
     for table in `cat $staged`; do
         echo "removing '$table'" >>$log
         mysql $db -p"$PASSWORD" -e"drop view if exists $table; drop table if exists $table;" 2>$last_error
         if [ -s $last_error ]; then
             let errors++;
-            cat $last_error >>$log
+            echo "[WW] error during removal: $(cat $last_error)" >>$log
         fi
     done
     if [ $errors = 0 ]; then
         break
     else
-        echo "removal failed, looping" >>$log
+        echo "[WW] removal failed with $errors error(s)" >>$log
         errors=0
     fi
     let tries++
 done
 if [ $errors -gt 0 ]; then
-    echo "removed failed after 20 tries" >>$log
-    echo "$0: could not remove all tables. see $log for details" 1>&2
+    echo "[EE] remove failed after 20 tries" >>$log
+    echo "db: could not remove all tables. see $log for details" 1>&2
     exit 2
 fi
 
-remaining=`mysql $db -p"$PASSWORD" -e 'show tables'`
-if [ "$?" != 0 ]; then
+if ! mysql $db -p"$PASSWORD" -e"truncate patches; truncate patch_changelog"; then
     exit 2
 fi
-if echo $remaining | egrep '[^[:space:]]' >/dev/null; then
-    echo 'The following untracked tables were ignored:'
-    set $remaining;shift
-    echo $* | sed 's/ /\n/g'
+
+if [ $(get_tables | . db-filter-tables.sh | wc -l) > 0 ]; then 
+    echo 'The following untracked tables were not removed:'
+    get_tables | . db-filter-tables.sh;
 fi;
