updated db-update's error format

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -118,11 +118,11 @@ do
             +*) 
                 table=${table:1};
                 if egrep -x "$table" <$tables_before >/dev/null; then
-                    echo "$0: patchlist: '$table' existed before '$patch_name' was executed" 1>&2
+                    echo "db: '$table' existed before '$patch_name' was executed" 1>&2
                     exit 1
                 fi
                 if ! egrep -x "$table" <$tables_after >/dev/null; then
-                    echo "$0: patchlist: '$table' does not exist, even though '$patch_name' claimed to have created it" 1>&2
+                    echo "db: '$table' does not exist, even though '$patch_name' claimed to have created it" 1>&2
                     exit 1
                 fi
                 log_table 'create' $patch_name ${line:1} ;log_table 'create' $patch_name ${line:1}
@@ -130,11 +130,11 @@ do
             -*) 
                 table=${table:1};
                 if ! egrep -x "$table" <$tables_before >/dev/null; then
-                    echo "$0: patchlist: '$table' does not exist, and could not have been removed by '$patch_name'" 1>&2
+                    echo "db: '$table' does not exist, and could not have been removed by '$patch_name'" 1>&2
                     exit 1
                 fi
                 if egrep -x "$table" <$tables_after >/dev/null; then
-                    echo "$0: patchlist: '$table' still exists, even though '$patch_name' claimed to have removed it" 1>&2
+                    echo "db '$table' still exists, even though '$patch_name' claimed to have removed it" 1>&2
                     exit 1
                 fi
                 log_table 'drop' $patch_name ${line:1} 
